# Numpy
---

In [1]:
import numpy as np

In [3]:
print(np.__version__)
np.show_config

1.24.3


<function numpy.__config__.show()>

In [6]:
Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
Z1 = np.zeros(10)
Z1[4] = 1
Z1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [8]:
vector1 = np.arange(10,50)
vector1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [9]:
vector2 = vector1[::-1]
vector2

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [11]:
vector3 = np.arange(9)
matrix1 = vector3.reshape(3,3)
matrix1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
matrix2 = np.eye(3)
matrix2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
array1 = np.random.random((3,3,3))
array1

array([[[0.42463413, 0.06390998, 0.35269674],
        [0.01934585, 0.1370146 , 0.79578217],
        [0.59462616, 0.67873083, 0.73786038]],

       [[0.39634204, 0.07900954, 0.76574689],
        [0.14826967, 0.86048399, 0.03323096],
        [0.06557437, 0.64203661, 0.82806186]],

       [[0.33161119, 0.68059904, 0.05853022],
        [0.2039699 , 0.39994494, 0.2718103 ],
        [0.95658221, 0.51197394, 0.40456209]]])

In [18]:
array2 = np.random.random((10,10))
print(array2)
print(array2.max())
print(array2.min())

[[0.67662685 0.04137333 0.18208228 0.82165005 0.7275666  0.74400784
  0.58621213 0.89422396 0.85420754 0.66141346]
 [0.09525214 0.13045792 0.51908196 0.87772757 0.97004506 0.35554609
  0.0927864  0.24623439 0.3550336  0.231397  ]
 [0.7731703  0.49208801 0.09608857 0.36822    0.60037666 0.59231874
  0.42572247 0.41700387 0.91947098 0.55578173]
 [0.90097111 0.7637177  0.82258821 0.75344587 0.08716931 0.07836847
  0.13587008 0.94663333 0.47947649 0.02522131]
 [0.16431843 0.54398426 0.67342847 0.10576134 0.15647041 0.19421538
  0.43232302 0.94008061 0.47891469 0.68578138]
 [0.95325177 0.59484304 0.49204496 0.83628524 0.19381083 0.26064146
  0.69676122 0.02607831 0.68398172 0.13343266]
 [0.81375381 0.19893066 0.63435131 0.77861924 0.60254639 0.40737951
  0.5819095  0.7881822  0.85818521 0.69291266]
 [0.3069602  0.44703593 0.69024557 0.44386762 0.44665909 0.0706689
  0.02535798 0.16185705 0.30497991 0.55512271]
 [0.48008762 0.81970116 0.06809539 0.25073448 0.27998845 0.15094747
  0.02471092 

In [21]:
vector4 = np.random.random((30))
print(vector4)
print(vector4.mean())

[0.28342984 0.73404201 0.39394614 0.82500748 0.18430858 0.28403777
 0.14462661 0.5387479  0.77325808 0.14374366 0.43551133 0.92735081
 0.79197815 0.89801721 0.07631473 0.63302305 0.82762798 0.92976176
 0.42765407 0.78084383 0.9971266  0.38279545 0.48628718 0.20227202
 0.7167102  0.79364106 0.46893959 0.02215179 0.83406199 0.16987289]
0.536902992737774


In [27]:
array3 = np.ones((10,10))
array3[1:-1, 1:-1] = 0
array3

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [29]:
matrix3 = np.zeros((8,8), dtype=int)
matrix3[1::2, ::2] = 1
matrix3[::2, 1::2] = 1
print(matrix3)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [31]:
dot1 = np.dot(np.ones((5,3)), np.ones((3,2)))
print(dot1)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


# Pandas
---

In [33]:
import pandas as pd

In [39]:
df = pd.read_csv('c:/Example/games.csv')
df

gameId   creationTime  gameDuration  seasonId  winner  firstBlood  \
0      3326086514  1504279457970          1949         9       1           2   
1      3229566029  1497848803862          1851         9       1           1   
2      3327363504  1504360103310          1493         9       1           2   
3      3326856598  1504348503996          1758         9       1           1   
4      3330080762  1504554410899          2094         9       1           2   
...           ...            ...           ...       ...     ...         ...   
51485  3308904636  1503076540231          1944         9       2           1   
51486  3215685759  1496957179355          3304         9       2           1   
51487  3322765040  1504029863961          2156         9       2           2   
51488  3256675373  1499562036246          1475         9       2           2   
51489  3317333020  1503612754059          1445         9       1           1   

       firstTower  firstInhibitor  firstBaron  firstDragon  ...  \
0               1               1           1            1  ...   
1               1               1           0            1  ...   
2               1               1           1            2  ...   
3               1               1           1            1  ...   
4               1               1           1            1  ...   
...           ...             ...         ...          ...  ...   
51485           2               2           0            2  ...   
51486           1               2           2            2  ...   
51487           2               2           0            1  ...   
51488           2               2           0            2  ...   
51489           1               1           1            2  ...   

       t2_towerKills  t2_inhibitorKills  t2_baronKills  t2_dragonKills  \
0                  5                  0              0               1   
1                  2                  0              0               0   
2                  2                  0              0               1   
3                  0                  0              0               0   
4                  3                  0              0               1   
...              ...                ...            ...             ...   
51485             10                  2              0               4   
51486             11                  7              4               4   
51487             10                  2              0               2   
51488             11                  3              0               1   
51489              1                  0              0               1   

       t2_riftHeraldKills  t2_ban1  t2_ban2  t2_ban3  t2_ban4  t2_ban5  
0                       1      114       67       43       16       51  
1                       0       11       67      238       51      420  
2                       0      157      238      121       57       28  
3                       0      164       18      141       40       51  
4                       0       86       11      201      122       18  
...                   ...      ...      ...      ...      ...      ...  
51485                   0       55       -1       90      238      157  
51486                   1      157       55      119      154      105  
51487                   0      113      122       53       11      157  
51488                   0      154       39       51       90      114  
51489                   0       11      157      141       31       18  

[51490 rows x 61 columns]

In [40]:
df.head()

gameId   creationTime  gameDuration  seasonId  winner  firstBlood  \
0  3326086514  1504279457970          1949         9       1           2   
1  3229566029  1497848803862          1851         9       1           1   
2  3327363504  1504360103310          1493         9       1           2   
3  3326856598  1504348503996          1758         9       1           1   
4  3330080762  1504554410899          2094         9       1           2   

   firstTower  firstInhibitor  firstBaron  firstDragon  ...  t2_towerKills  \
0           1               1           1            1  ...              5   
1           1               1           0            1  ...              2   
2           1               1           1            2  ...              2   
3           1               1           1            1  ...              0   
4           1               1           1            1  ...              3   

   t2_inhibitorKills  t2_baronKills  t2_dragonKills  t2_riftHeraldKills  \
0                  0              0               1                   1   
1                  0              0               0                   0   
2                  0              0               1                   0   
3                  0              0               0                   0   
4                  0              0               1                   0   

   t2_ban1  t2_ban2  t2_ban3  t2_ban4  t2_ban5  
0      114       67       43       16       51  
1       11       67      238       51      420  
2      157      238      121       57       28  
3      164       18      141       40       51  
4       86       11      201      122       18  

[5 rows x 61 columns]

In [47]:
df.columns

Index(['gameId', 'creationTime', 'gameDuration', 'seasonId', 'winner',
       'firstBlood', 'firstTower', 'firstInhibitor', 'firstBaron',
       'firstDragon', 'firstRiftHerald', 't1_champ1id', 't1_champ1_sum1',
       't1_champ1_sum2', 't1_champ2id', 't1_champ2_sum1', 't1_champ2_sum2',
       't1_champ3id', 't1_champ3_sum1', 't1_champ3_sum2', 't1_champ4id',
       't1_champ4_sum1', 't1_champ4_sum2', 't1_champ5id', 't1_champ5_sum1',
       't1_champ5_sum2', 't1_towerKills', 't1_inhibitorKills', 't1_baronKills',
       't1_dragonKills', 't1_riftHeraldKills', 't1_ban1', 't1_ban2', 't1_ban3',
       't1_ban4', 't1_ban5', 't2_champ1id', 't2_champ1_sum1', 't2_champ1_sum2',
       't2_champ2id', 't2_champ2_sum1', 't2_champ2_sum2', 't2_champ3id',
       't2_champ3_sum1', 't2_champ3_sum2', 't2_champ4id', 't2_champ4_sum1',
       't2_champ4_sum2', 't2_champ5id', 't2_champ5_sum1', 't2_champ5_sum2',
       't2_towerKills', 't2_inhibitorKills', 't2_baronKills', 't2_dragonKills',
       't2_riftHer

In [48]:
df.columns[5]

'firstBlood'

In [50]:
df.iloc[2, 5]

2